### ISSUE TITLE
[bug] signalSlice: unable to call actionSources if selectors are defined

### ISSUE THREAD

**Issue by eac-nathan-price** [nartc/ngxtension-platform#213] opened 2024-01-04 07:32 UTC
Edit: Upon further testing the issue seems to be with calling actionSources in general when using selectors in signalSlice.

I created a new project and started rebuilding my state from scratch and actionSources and actionEffects all worked perfectly up until the moment the selectors key was set:

    selectors: (state) => ({ }),

It doesn't matter if any selectors are actually defined or not, as soon as that key is added to the signalSlice state, every place that was previously calling an actionSource successfully now shows the index signature error:

`Property 'someOtherAction' comes from an index signature, so it must be accessed with ['someOtherAction']`

---

~~There doesn't seem to be documentation for actionEffects so I'm not sure if their behavior was intended to be changed, but I have a situation similar to [one of the examples in the pr that added actionEffects](https://github.com/nartc/ngxtension-platform/pull/154#issue-1996560923):~~

    actionSources: {
      someAction:  (state, action$: Observable<void>) => action$.pipe(
        ...
      ),
      someOtherAction:  (state, action$: Observable<number>) => action$.pipe(
        ...
      )
    },
    actionEffects: (state) => ({
      someAction: (action) => {
        state.someOtherAction(1);
      },
    })

~~But it gives me the following typescript error:~~

`Property 'someOtherAction' comes from an index signature, so it must be accessed with ['someOtherAction']`

~~If I follow the suggestion of the error message and use:~~

    state['someOtherAction'](1);

~~Then I get the following error:~~

`Argument of type 'number' is not assignable to parameter of type '{ name: string; payload: never; value: never; err: any; }'`

~~So it seems actionSources are not being properly fed into the state variable used by actionEffects.~~

**Comment by eneajaho** [comment] 2024-01-04 12:04
cc @joshuamorony

**Comment by eac-nathan-price** [comment] 2024-01-04 20:36
Upon further testing the issue seems to be with calling actionSources in general when using selectors in signalSlice. I edited the title and post to reflect the new information.

**Comment by joshuamorony** [comment] 2024-01-04 23:01
Thanks for the issue and testing @eac-nathan-price - I think I have a fix for this here: https://github.com/joshuamorony/ngxtension-platform/commit/e8d7e18d8e7751a92f5c67b4ee403ee9f71290c7 just going to add some tests to make sure before opening a PR

The issue is that since the `selectors` is passed the entire `SignalSlice` it will infer all of the types for actionSources/actionEffects etc when the `selectors` config is passed in (at which time those other configurations have not been supplied yet). You would find that if you supply `selectors` after `actionSources` and `actionEffects` it would work, but this is confusing and causes other problems anyway (because other properties have a similar problem where they are passed the entire `SignalSlice`)

I've made a typing change so that rather than being passed the entire `SignalSlice` the `selectors` and others are only passed the subset of types that they actually need.

I'll try to get a PR up for this later today

**Comment by eac-nathan-price** [comment] 2024-01-05 00:11
Appreciate the fast turnaround @joshuamorony ! Your declarative tutorials and this library are finally letting me clean up a huge mess of imperative code.

Out of curiosity, is an actionEffect for the "all actions" stream still planned? I would love the ability to have multiple specified actionSources trigger the same actionEffect, but having an all-actions catch-all is pretty much just as good.

**Comment by joshuamorony** [comment] 2024-01-05 02:35
@eac-nathan-price potentially yes - the reason I've left `actionEffects` undocumented for now is I'm not 100% sure on the API or necessarily whether it should be included at all

The primary situation it solves is when an effect needs to run async in response to an action. Not including `actionEffects` strikes me as potentially a cleaner/more declarative approach - without actionEffects we just have sources/actionSources that update the state and you can react to the state changing if necessary with standard signal effects. However, for some situations this forces you to add unnecessary things to the state if you want to react to them - e.g. if you have an actionSource that doesn't actually change the state, but you want to react to it completing, you would have to do something like add some kind of flag to the state to indicate when the action completes, so that you can react to it with a standard signal effect.

Anyway, would love to hear any thoughts you have. I'm leaning toward including it (and likely an all actions stream/effect)

**Comment by eac-nathan-price** [comment] 2024-01-05 04:11
@joshuamorony In my app, depending on the parameters set by the user, hundreds of http requests might be needed. So what I'm trying to do first with signalSlice is to manage the state of a request queueing system. I have an actionSource which pushes request info to an array on the state, that then triggers an actionEffect which checks if a new request can be made at that moment. There are several book-keeping values on the state which are used for this, as well as providing descriptive progress indicators to the user. Suffice to say there are other actions for shifting request info out of the array on the state, as well as actually making the http request and storing its result in a collection on the state, and then an actionEffect after an http response is received to check if there are more waiting in the queue and to start the next one.

So I wind up bouncing back and forth between actionSources and actionEffects like a state machine. I'm not sure how this could be accomplished without actionEffects?

**Comment by joshuamorony** [comment] 2024-01-05 05:46
@eac-nathan-price it's hard to say of course without the full context, but my instinct is to not using effects as the mechanism for controlling the queue

I would think something like having some some subject external to the state that is nexted with whatever things are added to the queue, e.g:

```ts
queue$ = new Subject<string>();
```

You can add this subject to your signalSlice so that you still trigger adding to the queue through the signalSlice rather than manually nexting this subject

Then I would have the actual queue mechanism piped off of that, e.g:

```ts
stuffMyQueueEmits$ = queue$.pipe(concatMap or whatever)
```

You can use the RxJS pipe here to handle whatever kind of queueing/checks you need. Then this `stuffMyQueueEmits$` observable would be a source that sets stuff into the state of your signalSlice.

There is probably more you need to add here, but I assume something like this should avoid any need to use effects to manage your queue (and if you do need to trigger some side effect as the result of new data becoming available, you could do that with a standard signal effect - but generally those sorts of side effects should be rare). Feel free to reach out to me via email if you like since this issue will likely be closed soon.

**Closed** 2024-01-06 01:49 UTC
