### ISSUE TITLE
Swap computedFrom<Input, Output> to computedFrom<Output, Input>?

### ISSUE THREAD

**Issue by renatoaraujoc** [nartc/ngxtension-platform#73] opened 2023-09-19 16:54 UTC
Hello @nartc and @eneajaho,

After a talk with Enea on Twitter, I've shown that maybe we could improve computedFrom type inference.

Right now, we can't easily tell `computedFrom` what kind of Output type we want it to be unless we specify the Input params first.

Right now we need to do this:

```ts
someNumber = signal<number | null>(null);

computedNumberToSomething = computedFrom<[number | null], number>(
    [this.someNumber],
    pipe(map(([someNumber]) => someNumber ?? 0))
);
```

Could we have something like:

```ts
someNumber = signal<number | null>(null);

computedNumberToSomething = computedFrom<number>(
    [this.someNumber],
    pipe(map(([someNumber]) => someNumber ?? 0))
);
```

It would be needed to swap <Input, Output> to <Output, Input> in `computedFrom`.

Second feedback:

Create an overloaded function that also accepts a non readonly array, so we can:

```ts
someNumber = signal<number | null>(null);

computedNumberToSomething = computedFrom<number>(
    this.someNumber,
    pipe(map(([someNumber]) => someNumber ?? 0))
);
```

What yall think?

Renato

**Comment by nartc** [comment] 2023-09-20 15:10
Hey, the first feedback makes sense to me but I don't quite get the 2nd feedback. Can you elaborate a bit?

**Comment by tomer953** [comment] 2023-09-20 15:23
I think he wants to spread the args
ie in addition to `computedFrom([a,b,c])`
also support `computedFrom(a,b,c)`

**Comment by nartc** [comment] 2023-09-20 15:36
@tomer953 that's gonna be painful to type 😅 but totally understand the desire.

**Comment by renatoaraujoc** [comment] 2023-09-20 17:33
> Hey, the first feedback makes sense to me but I don't quite get the 2nd feedback. Can you elaborate a bit?

Hey Chau, yea I can elaborate.

The beauty of working with `computedFrom` is that it also accepts anything and you dont have to do miraculous stuff to get it going, it accepts `Observables` and `Signals`, right?

Use my last example: 

```ts

function filterNotNullOrUndefined<T>(
    input: null | undefined | T
): input is T {
    return input !== null && input !== undefined;
}

// I use this function alot in my codebase
function rxjsFilterNotNullOrUndefined<T>() {
    return (source$: Observable<null | undefined | T>) =>
        source$.pipe(filter(filterNotNullOrUndefined));
}

// Desirable
computedNumberToSomething = computedFrom<number>(
    this.someNumber, // imagine this is <number | null | undefined>
    // now I want to filter the typeguard function above
    rxjsFilterNotNullOrUndefined(),
    // number is NonNullable<number> here
    pipe(map((number) => someNumber + 1))
);

// Current
computedNumberToSomething = computedFrom<number>(
    [this.someNumber], // imagine this is <number | null | undefined>
    filter(([number]) => !!number), // typeguard won't infer the 1st param is NonNullable<number>
    pipe(map(([number]) => someNumber + 1 )) // Error: number can be undefined or null
);
```

Unless you have a better way to handle these situations, I'm all ears :)

Renato

**Comment by tomer953** [comment] 2023-09-20 18:02
> Unless you have a better way to handle these situations, I'm all ears :)

The problem you mentioned is not related to this library but its an [old and famous problem in typescript](https://github.com/microsoft/TypeScript/issues/16069)

<img width="466" alt="image" src="https://github.com/nartc/ngxtension-platform/assets/1807493/088e6cb8-fe4e-4a7d-9694-0448c6da1023">

**Comment by tomer953** [comment] 2023-09-20 18:05
B.t.w:
>  I use this function alot in my codebase

```ts
function filterNotNullOrUndefined<T>(
    input: null | undefined | T
): input is T {
    return input !== null && input !== undefined;
}

// I use this function alot in my codebase
function rxjsFilterNotNullOrUndefined<T>() {
    return (source$: Observable<null | undefined | T>) =>
        source$.pipe(filter(filterNotNullOrUndefined));
}
```

Check out the brand new `filterNil` operator
https://ngxtension.netlify.app/utilities/filter-nil/

**Comment by renatoaraujoc** [comment] 2023-09-21 02:46
> > Unless you have a better way to handle these situations, I'm all ears :)
> 
> The problem you mentioned is not related to this library but its an [old and famous problem in typescript](https://github.com/microsoft/TypeScript/issues/16069)
> 
> <img alt="image" width="466" src="https://user-images.githubusercontent.com/1807493/269376499-088e6cb8-fe4e-4a7d-9694-0448c6da1023.png">

Yea, I know this issue, but we can have some workarounds to mirigate this limitation, my suggestion was targeted for this.

**Comment by tomer953** [comment] 2023-09-21 03:35
Oh I see.

Small example to reproduce:

  ```ts
n = signal<number | undefined | null>(3);

    // filter with typeguard is working
    x$ = of(this.n()).pipe(
      filter((x): x is number => Boolean(x)),
      map((x) => (x as number) + 1)
    );
   
    // filterNil has typeguard already
    y$ = of(this.n()).pipe(
      filterNil(),
      map((x) => x + 1)
    );
  
    // but with computedFrom it failes to narrow
    z$ = computedFrom(
      [this.n],
      pipe(
        filterNil(),
        map(([x]) => x + 1) // x is possibly null or undefined
      )
    );
```

z$ should act like y$
I can’t find why this happens, @nartc  might help here

**Comment by nartc** [comment] 2023-09-21 10:31
I'll take a closer look this weekend.

**Comment by nartc** [comment] 2023-10-13 19:13
I now have time to take a look at this.
1. What happens if I don't want to use any operator with `computedFrom`? I simply want to combine some Signals and Observables together. Specifying the `Output` first won't allow me to default it to the type of the `Input`

3.
```ts
// Desirable
computedNumberToSomething = computedFrom<number>(
    this.someNumber, // imagine this is <number | null | undefined>
    pipe(
        // now I want to filter the typeguard function above, this is now NonNullable<number>
        rxjsFilterNotNullOrUndefined(),
        map((number) => someNumber + 1)
    )
);
```

Your desirable case won't work because what happens if:
```ts
// Desirable
computedNumberToSomething = computedFrom<number>(
    this.someNumber, // imagine this is <number | null | undefined>
    this.someOtherValue,
    pipe(
        // now I want to filter the typeguard function above, this is now NonNullable<number>
        rxjsFilterNotNullOrUndefined(), // now what happens?
        map((number) => someNumber + 1)
    )
);
```

Regardless of how we want `computedFrom` to accept (array, dictionary, or a rest arguments), the `pipe()` would still need to expect a collection of values of all the inputs. Take a look at this scenario

```ts
computedFrom(
    [of<number | null>(1), signal(2)],
    pipe(
        filter(([first]) => !!first), // here we're saying if first is falsy, then stream won't emit.
        map(([first, second]) => {}) 
    )
);

// in this case, I'd recommend
computedFrom(
    [of<number | null>(1).pipe(filterNil()), signal(2)],
    pipe(
        map(([first, second]) => {})
    )
)
```

**Comment by eneajaho** [comment] 2023-11-15 09:13
@renatoaraujoc looks like this is not doable. Is it ok if we close this?

**Comment by renatoaraujoc** [comment] 2023-11-15 11:25
Hey @eneajaho, it should be doable on next versions of TS but today it's definitely not. Let's close it :)

**Closed** 2023-11-15 11:26 UTC
